"""empty message

Revision ID: 3f585079962c
Revises: ba42c1d77469
Create Date: 2019-05-31 15:06:52.445766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f585079962c'
down_revision = 'ba42c1d77469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langstat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('fragments_counter', sa.Integer(), nullable=True),
    sa.Column('fragments_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('snippets', sa.Column('born_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippets', 'born_date')
    op.drop_table('langstat')
    # ### end Alembic commands ###
