"""empty message

Revision ID: 8b350ab206cb
Revises: 1b38c36f471d
Create Date: 2019-05-27 21:21:24.148084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b350ab206cb'
down_revision = '1b38c36f471d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('forms', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('forms', sa.Column('title', sa.String(), nullable=False))
    op.add_column('refs', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('snippets', sa.Column('public_flag', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippets', 'public_flag')
    op.drop_column('refs', 'lang')
    op.drop_column('forms', 'title')
    op.drop_column('forms', 'lang')
    op.drop_column('files', 'lang')
    # ### end Alembic commands ###
