"""empty message

Revision ID: b91d33016dd0
Revises: d9744eae5f0d
Create Date: 2019-05-31 21:13:13.598034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91d33016dd0'
down_revision = 'd9744eae5f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refs')
    op.drop_table('forms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snippets_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snippets_id'], ['snippets.id'], name='forms_snippets_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='forms_pkey')
    )
    op.create_table('refs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snippets_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ref', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['snippets_id'], ['snippets.id'], name='refs_snippets_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refs_pkey')
    )
    # ### end Alembic commands ###
