"""empty message

Revision ID: da525bcfd257
Revises: 8694b514a9c9
Create Date: 2019-06-01 18:26:48.919450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da525bcfd257'
down_revision = '8694b514a9c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'snippets_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('snippets_table_key', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'snippets', ['snippets_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('snippets_table_key', 'files', 'snippets', ['snippets_id'], ['id'], ondelete='CASCADE')
    op.alter_column('files', 'snippets_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
